for k=1:3
    if k==1
        load(strcat(Filename1,'.mat'))
    elseif k==2
        load(strcat(Filename2,'.mat'))
    elseif k==3
        load(strcat(Filename3,'.mat'))
    end
    for iteration = [1, size(pp,3)]
        f=figure;
        f.Position = [680 753 334 345];
        f.Color = 'W';
        X_stars = pp(:,:,iteration);
        X = splinepoints(pp(:,:,iteration),11);
        plot3(X(1,:),X(2,:),X(3,:),'-','LineWidth', 1,'Color','b', 'LineWidth', 2.5)
        hold all
        plot3(ones(size(X(1,:)))*4,X(2,:),X(3,:),'-k', 'LineWidth', 2.5)
        plot3(X(1,:),ones(size(X(2,:)))*4.001,X(3,:),'-k', 'LineWidth', 2.5)
        plot3(X(1,:),X(2,:),ones(size(X(3,:)))*(-4),'-k', 'LineWidth', 2.5)
        hold off
        axis equal
        axis([-4.,4.,-4.001,4.001,-4,4])
        set(gca,'fontsize',14)
        grid on
        set(gca,'GridAlpha', 0.2);
        set(gca,'LineWidth',2.,'TickLength',[0.025 0.04]);
        ax = gca;
        ax.XAxis.TickValues = [-4,-2,0,2,4];
        ax.YAxis.TickValues = [-4,-2,0,2,4];
        ax.ZAxis.TickValues = [-4,-2,0,2,4];
        ax.XAxis.TickLabels(5) = {''};
        hold off
        if iteration == 1
            str = " (initial curve)";
            form = '%10.0e';
            for2 = form;
            chirnum = iteration;
        else
            str = " (final result)";
            form = 2;
            for2 = 1;
            chirnum = iteration-1;
        end
        if k==1
                   text(3.11,-7.31,-1.21,{...
        strcat('$$J_{\rm{HS}}=$$',num2str(smooth_relax(chirnum),for2))}...
        ,'BackGroundColor','w',...
            'FontSize',18,'Interpreter','Latex',...
            'Edgecolor','k',...
            'LineStyle','-',...
            'LineWidth',1,...
            'Clipping','off',...
            'HorizontalAlignment', 'right',...
            'VerticalAlignment', 'top')
        elseif k==2
                    text(3.11,-7.31,-1.21,{...
        strcat('$$J_{\rm{HS}}=$$',num2str(smooth_relax(chirnum),for2))}...
        ,'BackGroundColor','w',...
            'FontSize',18,'Interpreter','Latex',...
            'Edgecolor','k',...
            'LineStyle','-',...
            'LineWidth',1,...
            'Clipping','off',...
            'HorizontalAlignment', 'right',...
            'VerticalAlignment', 'top')
        else
                    text(3.11,-7.31,-1.21,{...
        strcat('$$J_{\rm{HS}}=$$',num2str(smooth_relax(chirnum),for2))}...
        ,'BackGroundColor','w',...
            'FontSize',18,'Interpreter','Latex',...
            'Edgecolor','k',...
            'LineStyle','-',...
            'LineWidth',1,...
            'Clipping','off',...
            'HorizontalAlignment', 'right',...
            'VerticalAlignment', 'top')
        end
        title(strcat("$\ell=$",num2str(iteration-1),str),'Interpreter','Latex','FontSize',18)
        filename=strcat("PaperPlots/Plot1",num2str(k),"_",num2str(iteration));
        print(gcf,'-depsc',filename);
    end
end