for k=1:3
    if k==1
        load(strcat(Filename1,'.mat'))
    elseif k==2
        load(strcat(Filename2,'.mat'))
    elseif k==3
        load(strcat(Filename3,'.mat'))
    end
    for iteration = [1, size(pp,3)]
        f=figure;
        f.Position = [680 753 334 345];
        f.Color = 'W';
        X_stars = pp(:,:,iteration);
        X = splinepoints(pp(:,:,iteration),11);
        plot3(X(1,:),X(2,:),X(3,:),'-','LineWidth', 1,'Color','b', 'LineWidth', 2.5)
        hold all
        plot3(ones(size(X(1,:)))*7,X(2,:),X(3,:),'-k', 'LineWidth', 2.5)
        plot3(X(1,:),ones(size(X(2,:)))*7.001,X(3,:),'-k', 'LineWidth', 2.5)
        plot3(X(1,:),X(2,:),ones(size(X(3,:)))*(-7),'-k', 'LineWidth', 2.5)
        hold off
        axis equal
        axis([-7.,7.,-7.001,7.001,-7,7])
        set(gca,'fontsize',14)
        grid on
        set(gca,'GridAlpha', 0.2);
        set(gca,'LineWidth',2.,'TickLength',[0.025 0.04]);
        ax = gca;
        ax.XAxis.TickValues = [-7,-5,-3,-1,1,3,5,7];
        ax.YAxis.TickValues = [-7,-5,-3,-1,1,3,5,7];
        ax.ZAxis.TickValues = [-7,-5,-3,-1,1,3,5,7];
        ax.XAxis.TickLabels(7) = {''};
        ax.XAxis.TickLabels(8) = {''};
        hold off
        if iteration == 1
            str = " (initial guess)";
            form = '%10.0e';
            chirnum = iteration;
            for2 = form;
        else
            str = " (final result)";
            form = 2;
            chirnum = iteration-1;
            for2 = 2;
        end
        if k==1
            text(7.31,-9.99,-4.66,{...
        strcat('$$J_{\rm{HS}}=$$',num2str(smooth_relax(chirnum),for2))}...
        ,'BackGroundColor','w',...
            'FontSize',18,'Interpreter','Latex',...
            'Edgecolor','k',...
            'LineStyle','-',...
            'LineWidth',1,...
            'Clipping','off',...
            'HorizontalAlignment', 'right',...
            'VerticalAlignment', 'top')
        elseif k==2
            text(7.31,-9.99,-4.66,{...
        strcat('$$J_{\rm{HS}}=$$',num2str(smooth_relax(chirnum),for2))}...
        ,'BackGroundColor','w',...
            'FontSize',18,'Interpreter','Latex',...
            'Edgecolor','k',...
            'LineStyle','-',...
            'LineWidth',1,...
            'Clipping','off',...
            'HorizontalAlignment', 'right',...
            'VerticalAlignment', 'top')
        else
            text(7.31,-9.99,-4.66,{...
        strcat('$$J_{\rm{HS}}=$$',num2str(smooth_relax(chirnum),for2))}...
        ,'BackGroundColor','w',...
            'FontSize',18,'Interpreter','Latex',...
            'Edgecolor','k',...
            'LineStyle','-',...
            'LineWidth',1,...
            'Clipping','off',...
            'HorizontalAlignment', 'right',...
            'VerticalAlignment', 'top')
        end
        title(strcat("$\ell=$",num2str(iteration-1),str),'Interpreter','Latex','FontSize',18)
        filename=strcat("PaperPlots/Plot2",num2str(k),"_",num2str(iteration));
        print(gcf,'-depsc',filename);    
    end
end